### ISSUE TITLE
Issue with place oto order

### ISSUE THREAD

**Issue by jbonde32** [tedchou12/webull#216]
When using the place_order_otoco function, getting error:
 
   if result1['forward'] :
KeyError: 'forward'

Maybe the forward name changed?

**Comment by Jakezheng** [comment]
same problem

**Comment by Jakezheng** [comment]
{'msg': 'Inner server error', 'traceId': '**********************', 'code': 'trade.secAcct.mismatch.with.user', 'data': {}, 'success': False}

**Comment by tedchou12** [comment]
this should be fixed. Let me know if you still have troubles

**Comment by jbonde32** [comment]
Hey just tried this again and still getting the error. The line of code i'm running is:

wb.place_order_otoco(stock = stock,
                     price = price,
                     stop_loss_price = stop_loss,
                     limit_profit_price = take_prof,
                     time_in_force = 'gtc',
                     quant = shares)

Still receiving this error:
![image](https://user-images.githubusercontent.com/82673309/117464670-8296e300-af16-11eb-9995-f0e141211fb9.png)

**Comment by tedchou12** [comment]
@jbonde32 
How did you install the new package? I didn't upload to pypi yet, so you would have to download it from github and install directly.
